/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyseIndexRouteImport } from './routes/analyse.index'
import { Route as AnalyseListenRouteImport } from './routes/analyse.listen'
import { Route as AnalyseMeasureRouteImport } from './routes/analyse.measure'
import { Route as AnalysePredictRouteImport } from './routes/analyse.predict'
import { Route as AnalyseWhyRouteImport } from './routes/analyse.why'
import { Route as ProcessIndexRouteImport } from './routes/process.index'
import { Route as ProcessRecordRouteImport } from './routes/process.record'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseIndexRoute = AnalyseIndexRouteImport.update({
  id: '/analyse/',
  path: '/analyse/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseListenRoute = AnalyseListenRouteImport.update({
  id: '/analyse/listen',
  path: '/analyse/listen',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseMeasureRoute = AnalyseMeasureRouteImport.update({
  id: '/analyse/measure',
  path: '/analyse/measure',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysePredictRoute = AnalysePredictRouteImport.update({
  id: '/analyse/predict',
  path: '/analyse/predict',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseWhyRoute = AnalyseWhyRouteImport.update({
  id: '/analyse/why',
  path: '/analyse/why',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessIndexRoute = ProcessIndexRouteImport.update({
  id: '/process/',
  path: '/process/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRecordRoute = ProcessRecordRouteImport.update({
  id: '/process/record',
  path: '/process/record',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyse/listen': typeof AnalyseListenRoute
  '/analyse/measure': typeof AnalyseMeasureRoute
  '/analyse/predict': typeof AnalysePredictRoute
  '/analyse/why': typeof AnalyseWhyRoute
  '/process/record': typeof ProcessRecordRoute
  '/analyse/': typeof AnalyseIndexRoute
  '/process/': typeof ProcessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyse/listen': typeof AnalyseListenRoute
  '/analyse/measure': typeof AnalyseMeasureRoute
  '/analyse/predict': typeof AnalysePredictRoute
  '/analyse/why': typeof AnalyseWhyRoute
  '/process/record': typeof ProcessRecordRoute
  '/analyse': typeof AnalyseIndexRoute
  '/process': typeof ProcessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyse/listen': typeof AnalyseListenRoute
  '/analyse/measure': typeof AnalyseMeasureRoute
  '/analyse/predict': typeof AnalysePredictRoute
  '/analyse/why': typeof AnalyseWhyRoute
  '/process/record': typeof ProcessRecordRoute
  '/analyse/': typeof AnalyseIndexRoute
  '/process/': typeof ProcessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyse/listen'
    | '/analyse/measure'
    | '/analyse/predict'
    | '/analyse/why'
    | '/process/record'
    | '/analyse/'
    | '/process/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyse/listen'
    | '/analyse/measure'
    | '/analyse/predict'
    | '/analyse/why'
    | '/process/record'
    | '/analyse'
    | '/process'
  id:
    | '__root__'
    | '/'
    | '/analyse/listen'
    | '/analyse/measure'
    | '/analyse/predict'
    | '/analyse/why'
    | '/process/record'
    | '/analyse/'
    | '/process/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyseListenRoute: typeof AnalyseListenRoute
  AnalyseMeasureRoute: typeof AnalyseMeasureRoute
  AnalysePredictRoute: typeof AnalysePredictRoute
  AnalyseWhyRoute: typeof AnalyseWhyRoute
  ProcessRecordRoute: typeof ProcessRecordRoute
  AnalyseIndexRoute: typeof AnalyseIndexRoute
  ProcessIndexRoute: typeof ProcessIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse/': {
      id: '/analyse/'
      path: '/analyse'
      fullPath: '/analyse/'
      preLoaderRoute: typeof AnalyseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse/listen': {
      id: '/analyse/listen'
      path: '/analyse/listen'
      fullPath: '/analyse/listen'
      preLoaderRoute: typeof AnalyseListenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse/measure': {
      id: '/analyse/measure'
      path: '/analyse/measure'
      fullPath: '/analyse/measure'
      preLoaderRoute: typeof AnalyseMeasureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse/predict': {
      id: '/analyse/predict'
      path: '/analyse/predict'
      fullPath: '/analyse/predict'
      preLoaderRoute: typeof AnalysePredictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse/why': {
      id: '/analyse/why'
      path: '/analyse/why'
      fullPath: '/analyse/why'
      preLoaderRoute: typeof AnalyseWhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process/': {
      id: '/process/'
      path: '/process'
      fullPath: '/process/'
      preLoaderRoute: typeof ProcessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process/record': {
      id: '/process/record'
      path: '/process/record'
      fullPath: '/process/record'
      preLoaderRoute: typeof ProcessRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyseListenRoute: AnalyseListenRoute,
  AnalyseMeasureRoute: AnalyseMeasureRoute,
  AnalysePredictRoute: AnalysePredictRoute,
  AnalyseWhyRoute: AnalyseWhyRoute,
  ProcessRecordRoute: ProcessRecordRoute,
  AnalyseIndexRoute: AnalyseIndexRoute,
  ProcessIndexRoute: ProcessIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
